name: tsc
on: [push]

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules Peperomia
      uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-Peperomia-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys:
          ${{ runner.os }}-Peperomia-
    - name: Install node_modules Peperomia
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: app copy
      run: yarn app:copy
    - name: codegen
      run: yarn codegen
    - name: tsc Peperomia
      run: yarn tsc

